from app.sources.base import Shoe


CATALOG: list[Shoe] = [
    Shoe(
        id="nb-550-au-lait",
        name="NB 550 'Au Lait'",
        brand="New Balance",
        notes="The grail: creamy vintage court energy with soft suede warmth.",
        image_url="/shoes/nb-550-au-lait.png",
        v={
            "chunk": 0.55,
            "retro": 0.92,
            "warm": 0.88,
            "minimal": 0.72,
            "earthy": 0.82,
            "loud": 0.28,
            "techy": 0.08,
        },
    ),
    Shoe(
        id="asics-gel-kayano-14-cream-black",
        name="ASICS Gel-Kayano 14 Cream Black",
        brand="ASICS",
        image_url="/shoes/asics-gel-kayano-14-cream-black.png",
        v={
            "chunk": 0.68,
            "retro": 0.62,
            "warm": 0.46,
            "minimal": 0.35,
            "earthy": 0.28,
            "loud": 0.48,
            "techy": 0.74,
        },
    ),
    Shoe(
        id="salomon-xt-6-safari",
        name="Salomon XT-6 Safari",
        brand="Salomon",
        image_url="/shoes/salomon-xt-6-safari.png",
        v={
            "chunk": 0.62,
            "retro": 0.22,
            "warm": 0.74,
            "minimal": 0.30,
            "earthy": 0.76,
            "loud": 0.58,
            "techy": 0.92,
        },
    ),
    Shoe(
        id="nike-air-max-1-crepe-hemp",
        name="Nike Air Max 1 Crepe Hemp",
        brand="Nike",
        image_url="/shoes/nike-air-max-1-crepe-hemp.png",
        v={
            "chunk": 0.50,
            "retro": 0.84,
            "warm": 0.82,
            "minimal": 0.58,
            "earthy": 0.90,
            "loud": 0.34,
            "techy": 0.22,
        },
    ),
    Shoe(
        id="adidas-samba-wales-bonner-fox-brown",
        name="adidas Samba Wales Bonner Fox Brown",
        brand="adidas",
        image_url="/shoes/adidas-samba-wales-bonner-fox-brown.png",
        v={
            "chunk": 0.16,
            "retro": 0.90,
            "warm": 0.86,
            "minimal": 0.70,
            "earthy": 0.74,
            "loud": 0.42,
            "techy": 0.05,
        },
    ),
    Shoe(
        id="reebok-club-c-85-vintage-chalk",
        name="Reebok Club C 85 Vintage Chalk",
        brand="Reebok",
        image_url="/shoes/reebok-club-c-85-vintage-chalk.png",
        v={
            "chunk": 0.22,
            "retro": 0.88,
            "warm": 0.68,
            "minimal": 0.88,
            "earthy": 0.54,
            "loud": 0.10,
            "techy": 0.02,
        },
    ),
    Shoe(
        id="mizuno-wave-rider-10-silver-cloud",
        name="Mizuno Wave Rider 10 Silver Cloud",
        brand="Mizuno",
        image_url="/shoes/mizuno-wave-rider-10-silver-cloud.png",
        v={
            "chunk": 0.58,
            "retro": 0.52,
            "warm": 0.30,
            "minimal": 0.34,
            "earthy": 0.20,
            "loud": 0.44,
            "techy": 0.80,
        },
    ),
    Shoe(
        id="hoka-tor-ultra-low-oat-milk",
        name="Hoka Tor Ultra Low Oat Milk",
        brand="Hoka",
        image_url="/shoes/hoka-tor-ultra-low-oat-milk.png",
        v={
            "chunk": 0.86,
            "retro": 0.28,
            "warm": 0.78,
            "minimal": 0.42,
            "earthy": 0.84,
            "loud": 0.36,
            "techy": 0.72,
        },
    ),
    Shoe(
        id="clarks-wallabee-maple-suede",
        name="Clarks Wallabee Maple Suede",
        brand="Clarks",
        image_url="/shoes/clarks-wallabee-maple-suede.png",
        v={
            "chunk": 0.34,
            "retro": 0.82,
            "warm": 0.92,
            "minimal": 0.76,
            "earthy": 0.96,
            "loud": 0.16,
            "techy": 0.00,
        },
    ),
    Shoe(
        id="on-cloudmonster-undyed-white",
        name="On Cloudmonster Undyed White",
        brand="On",
        image_url="/shoes/on-cloudmonster-undyed-white.png",
        v={
            "chunk": 0.78,
            "retro": 0.08,
            "warm": 0.36,
            "minimal": 0.64,
            "earthy": 0.22,
            "loud": 0.30,
            "techy": 0.88,
        },
    ),
    Shoe(
        id="new-balance-9060-sea-salt",
        name="New Balance 9060 Sea Salt",
        brand="New Balance",
        image_url="/shoes/new-balance-9060-sea-salt.png",
        v={
            "chunk": 0.84,
            "retro": 0.56,
            "warm": 0.60,
            "minimal": 0.48,
            "earthy": 0.54,
            "loud": 0.40,
            "techy": 0.42,
        },
    ),
    Shoe(
        id="nike-acg-mountain-fly-low-brown-basalt",
        name="Nike ACG Mountain Fly Low Brown Basalt",
        brand="Nike ACG",
        image_url="/shoes/nike-acg-mountain-fly-low-brown-basalt.png",
        v={
            "chunk": 0.72,
            "retro": 0.20,
            "warm": 0.80,
            "minimal": 0.28,
            "earthy": 0.88,
            "loud": 0.54,
            "techy": 0.86,
        },
    ),
    Shoe(
        id="puma-palermo-vine-clementine",
        name="Puma Palermo Vine Clementine",
        brand="Puma",
        image_url="/shoes/puma-palermo-vine-clementine.png",
        v={
            "chunk": 0.20,
            "retro": 0.86,
            "warm": 0.76,
            "minimal": 0.54,
            "earthy": 0.46,
            "loud": 0.66,
            "techy": 0.04,
        },
    ),
    Shoe(
        id="merrell-moab-3-taupe",
        name="Merrell Moab 3 Taupe",
        brand="Merrell",
        image_url="/shoes/merrell-moab-3-taupe.png",
        v={
            "chunk": 0.66,
            "retro": 0.38,
            "warm": 0.78,
            "minimal": 0.46,
            "earthy": 0.92,
            "loud": 0.18,
            "techy": 0.58,
        },
    ),
    Shoe(
        id="maison-margiela-replica-gat-cream",
        name="Maison Margiela Replica GAT Cream",
        brand="Maison Margiela",
        image_url="/shoes/maison-margiela-replica-gat-cream.png",
        v={
            "chunk": 0.18,
            "retro": 0.78,
            "warm": 0.64,
            "minimal": 0.82,
            "earthy": 0.48,
            "loud": 0.20,
            "techy": 0.02,
        },
    ),
]
